#pragma once


#define EE_HANDS

#define SPI_DRIVER SPID1
#define SPI_SCK_PIN  GP14
#define SPI_MOSI_PIN GP15
#define SPI_MISO_PIN GP12
#define POINTING_DEVICE_CS_PIN GP13
#define PMW3389_CS_PIN GP13

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET

#define SPLIT_USB_DETECT
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_PIN_SWAP
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_COMBINED
#define POINTING_DEVICE_DEBUG